splunk/addonfactory-workflow-addon-release

.github/CODEOWNERS
.github/dependabot.yml
.github/workflows/agreements.yaml
.github/workflows/build-test-release.yaml
.github/workflows/release-notes.yaml
.github/workflows/reusable-build-test-release.yml
.licenserc.yaml
.pre-commit-config.yaml
.releaserc
LICENSE

Tested with:
https://github.com/splunk/splunk-add-on-for-jira-cloud/runs/4508605425?check_suite_focus=true

feat: initial workflow

---

.github/workflows/reusable-build-test-release.yml

JIRA: https://splunk.atlassian.net/browse/INFRA-35395

feat: job validating pr title

---

.github/workflows/reusable-build-test-release.yml

* feat: allow trufflehog false positive
* Update reusable-build-test-release.yml
Co-authored-by: kkania-splunk <76955023+kkania-splunk@users.noreply.github.com>

feat: allow trufflehog false positive (#27)

---

.github/workflows/reusable-build-test-release.yml

This is a temporary fix to unblock CI. We will investigate the root cause and then deliver a permanent fix

fix: hardcoding poetry version to 1.1.15

---

.github/workflows/reusable-build-test-release.yml

feat: add skynet logging

---

.github/workflows/reusable-build-test-release.yml

This PR can be merged after newer version of appinspect-cli-action is released

feat: updated version of appinspect cli action 

---

.github/workflows/reusable-build-test-release.yml

Setup workflow stage is added, in which step for skipping entire workflow and setup for delay destroy is added. Also, condition for pre-publish is updated.

ci: Added stage for skip workflow if description is empty

---

.github/workflows/reusable-build-test-release.yml

- Added support to preserve infrastructure if **_preserve_infra_** label is applied to PR
- If a workflow is triggered by the PR label, test types mentioned in the PR description after **_preserve:_** will execute.
- If a workflow is triggered by the PR label and the description is empty/invalid, the workflow will be skipped.
- Failed pre-publish stage if a workflow is triggered on the labeled run.

feat: Preserve Splunk Infrastructure

---

.github/workflows/reusable-build-test-release.yml

- Added support to collect diag in artifacts for the failing test types.

feat: Generate diag when test fails

---

.github/workflows/reusable-build-test-release.yml

This PR resolves a typo I noticed during a CI run.

Fix typo in CI

---

.github/workflows/reusable-escu-manual-workflow.yml

fix: bump splunk/addonfactory-test-matrix-action to v1.9

---

.github/workflows/reusable-build-test-release.yml
README.md

Introduced new step configure-tests-on-labels to job setup-workflow.
This step is enabling workflow users to trigger test execution based on labels attached to PR.
Additional info in updated README

feat: label handling for reusable workflow

---

.github/workflows/reusable-build-test-release.yml

chore: replace link with directions for LastPass in all other places

---

.github/workflows/reusable-build-test-release.yml
README.md

Tested here: 
https://github.com/splunk/splunk-add-on-for-google-workspace/actions/runs/5555742121/jobs/10185146305
https://github.com/splunk/splunk-add-on-for-cisco-meraki/actions/runs/5576114853

feat: Add Appinspect API action

---

.github/workflows/reusable-build-test-release.yml

This reverts commit e1a8b3d6854d7e1bba25fefdb70fa9bda3994a5e.

chore: revert "feat(poetry): bump poetry version to v1.5.1 (#190)"

---

.github/workflows/reusable-build-test-release.yml

* chore(deps): bump poetry version to 1.5.1
* feat: update splunk/addonfactory-ucc-generator-action to v2
---------

feat(poetry): bump poetry version to v1.5.1 (#190)

---

.github/workflows/reusable-build-test-release.yml

tested here: https://github.com/splunk/splunk-add-on-for-crowdstrike-fdr/actions/runs/7610192878?pr=822

fix: openapi artifact path

---

.github/workflows/build-test-branch.yml

THis PR introduces initial version of https://splunk.atlassian.net/browse/ADDON-67703 implementation.
Correlated with: https://github.com/splunk/addonfactory-repository-template/pull/528

chore: changes for  tests automation

---

.github/workflows/branch-test-release.yml
.github/workflows/build-test-branch.yml

THis PR introduces initial version of
https://splunk.atlassian.net/browse/ADDON-67703 implementation. Correlated with:
https://github.com/splunk/addonfactory-repository-template/pull/528

chore: introduction of test branch workflow  (#223)

---

.github/workflows/reusable-build-test-release.yml

Same as in https://github.com/splunk/addonfactory-workflow-addon-release/pull/228.

fix: remove Firefox from UI tests

---

README.md

We need to merge bug fixes with "squash commit" option so we don't have duplicate commit messages when new release is created.

docs: bug fix merge type update

---

.github/workflows/reusable-build-test-release.yml

This PR decommissions use of splunk/addonfactory-get-splunk-package-version-action, replacing it with the direct code.
https://splunk.atlassian.net/browse/ADDON-68236
Tested here: https://github.com/splunk/test-addonfactory-repo/actions/runs/7817333993/job/21325041323

refactor: remove addonfactory-get-splunk-package-version-action

---

.github/workflows/reusable-build-test-release.yml

[https://github.com/splunk/appinspect-cli-action/releases/tag/v2.5.0](url)
[https://dev.splunk.com/enterprise/docs/relnotes/relnotes-appinspectcli/whatsnew/#v3502024-03-27](url)
[https://github.com/splunk/splunk-add-on-for-google-workspace/actions/runs/8464669953](url)

fix: update AppInspect CLI action to v2.5 #247

---

.licenserc.yaml
runbooks/update_appinspect_cli_action.md

This PR adds a runbook to update AppInspect CLI Action.

docs: add a runbook to update AppInspect CLI Action

---

.github/workflows/reusable-build-test-release.yml

Test run: https://github.com/splunk/splunk-add-on-for-microsoft-sysmon/actions/runs/8646585224

fix: update appinspect-cli-action to v2.6

---

.github/workflows/build-test-release.yaml

Changes update-semver action from haya14busa to splunk owned one
JIRA: https://splunk.atlassian.net/browse/ADDON-68596

ci: add splunk update semver

---

.github/workflows/reusable-build-test-release.yml

This PR resumes partioned builds creation. 
Jira: https://splunk.atlassian.net/browse/ADDON-72517 
Test run: https://github.com/splunk/splunk-add-on-for-mysql/actions/runs/9890730582 (the partial packages are contained in `package-deployment` artifact)

fix: add build partitioning

---

.github/workflows/reusable-build-test-release.yml

This PR resumes partioned builds creation. 
Jira: https://splunk.atlassian.net/browse/ADDON-72517  Test run:
https://github.com/splunk/splunk-add-on-for-mysql/actions/runs/9890730582 (the partial packages are contained in `package-deployment` artifact)

fix: add build partitioning (#297)

---

.github/workflows/reusable-build-test-release.yml

Test run: https://github.com/splunk/splunk-add-on-for-microsoft-sysmon/pull/322/checks

feat: update appinpsect_cli_action to 2.8

---

.github/workflows/reusable-build-test-release.yml

Adjusting workflow trigger on `develop` branch to revert unnecessary change in https://github.com/splunk/addonfactory-workflow-addon-release/pull/309

chore: adjust workflow trigger on develop

---

.github/workflows/reusable-build-test-release.yml

Test run: https://github.com/splunk/splunk-add-on-for-google-cloud-platform/pull/757

fix: unique name for diag artifacts for marker runs

---

.github/workflows/reusable-build-test-release.yml

tests: https://github.com/splunk/splunk-add-on-for-google-cloud-platform/actions/runs/10619286231

fix: update path for argo logs pull from s3

---

.github/workflows/reusable-build-test-release.yml

fix: ga summary report scripted input filename fix

fix: scripted inputs summary

---

.github/workflows/reusable-build-test-release.yml

test run: https://github.com/splunk/splunk-add-on-for-google-cloud-platform/actions/runs/10643905753

fix: modinput issues

---

.github/workflows/build-test-release.yaml
.github/workflows/reusable-build-test-release.yml

Test-run: https://github.com/splunk/splunk-add-on-for-github-audit-log-monitoring/actions/runs/11323955274

fix: updating github test runner

---

runbooks/addonfactory-workflow-addon-release-docker-images.md

This PR contains minor changes in documentation.

docs: minor changes

---

.github/workflows/reusable-build-test-release.yml

Correlated PR: https://github.com/splunk/appinspect-cli-action/pull/136
- https://github.com/splunk/splunk-add-on-for-cisco-asa/actions/runs/13198034547
- https://github.com/splunk/splunk-add-on-for-salesforce/actions/runs/13197794456

feat: update AppInspect CLI action to 2.9

---

.github/workflows/reusable-build-test-release.yml

feat: release SPL2 testing flow for TAs (ADDON-78270)

---

.github/workflows/reusable-build-test-release.yml

https://github.com/splunk/splunk-add-on-for-palo-alto-networks/actions/runs/13459404695/job/37614069994

fix: Migrate SPL2 testing image to private GHCR repo (ADDON-78425)

---

.github/workflows/reusable-build-test-release.yml

fix: Use new framework in TA tests (ADDON-78658)

---

.github/workflows/reusable-build-test-release.yml

This PR fixes failing pre-publish job and introduces passing output to publish job instead.
Publish done:
https://github.com/splunk/test-addonfactory-repo/actions/runs/13566246210/job/37920798879
Publish skipped:
https://github.com/splunk/test-addonfactory-repo/actions/runs/13565248938
https://github.com/splunk/test-addonfactory-repo/actions/runs/13548190067/job/37866019352

fix: change conditions for pre-publish

---

.github/workflows/reusable-build-test-release.yml

chore: pre-release comments addressed

---

.github/workflows/reusable-build-test-release.yml

[ [ADDON-78394](https://splunk.atlassian.net/browse/ADDON-78394) ] Added conditions skip tests, build, app-inspect and publish if the changes in PR are only related to documentation.
Tests: https://docs.google.com/document/d/1IFxbIwzDM0lBkO3ciNxFrPlOPPE9YQhcaVStQg7lYEM/edit?usp=sharing 

feat: skip tests on docs only change

---

.github/workflows/reusable-build-test-release.yml
README.md

This PR bumps the k8s-manifests-branch version from v3.3.2 to v3.4.1
related PR: https://github.com/splunk/ta-automation-k8s-manifests/pull/120
- https://github.com/splunk/splunk-add-on-for-unix-and-linux/actions/runs/14701563721

fix: hec token validation issue in scripted inputs

---

.github/workflows/reusable-build-test-release.yml
README.md
runbooks/update_appinspect_cli_action.md

###
The file `.github/workflows/reusable-build-test-release.yml` had merge conflicts when merging develop into main.
This PR resolves those conflicts and syncs the changes accordingly.

chore: sync main into develop after conflict resolution

---

.github/workflows/reusable-build-test-release.yml

Test run: 
https://github.com/splunk/splunk-add-on-for-github-audit-log-monitoring/actions/runs/14998008338/job/42137066553
https://github.com/splunk/splunk-add-on-for-salesforce/actions/runs/15015649052/job/42192839796

fix: update python version for lint

---

.github/workflows/reusable-build-test-release.yml

Resolving develop -> main conflict

Resolve merge conflict 

---

.github/workflows/reusable-build-test-release.yml

chore: sync develop with main

---

.github/workflows/reusable-build-test-release.yml
runbooks/update_appinspect_cli_action.md

chore: merge main

---

.github/workflows/reusable-build-test-release.yml

chore: adjust manifests branch

---

.github/workflows/reusable-build-test-release.yml

chore: merge main to develop

---

.github/workflows/reusable-build-test-release.yml

This PR introduces mechanism for splitting dev dependencies from pyproject.toml and putting them to into dev_deps/requirements_dev.txt file. This is breaking change and needs to be performed before relevant repository template rollout.
https://github.com/splunk/splunk-add-on-for-cisco-asa/pull/465
https://github.com/splunk/splunk-add-on-for-amazon-web-services/pull/1532
https://github.com/splunk/splunk-add-on-for-google-workspace/pull/651
https://github.com/splunk/splunk-add-on-for-microsoft-office-365/pull/895
https://github.com/splunk/splunk-add-on-for-microsoft-cloud-services/pull/1363

feat: handle separate deps
