.github/workflows/reusable-build-test-release.yml

This PR is created for TA-aws using reusable workflow. Marker input is brought in to enable parallel run.
Related Jiras:
https://splunk.atlassian.net/browse/AQA-92
https://splunk.atlassian.net/browse/AQA-241

Add marker input

---

.github/workflows/reusable-build-test-release.yml

Make virustotal step optional since for larger files the step fails. Will require to implement a better github action for handling the large file scenario.

chor: make virustotal optional

---

.github/workflows/reusable-build-test-release.yml

This is not needed for the add-on repositories and it is causing issues (like, https://github.com/splunk/addonfactory-ucc-generator/issues/404).

fix: remove tags update

---

.github/workflows/reusable-build-test-release.yml

Upgrade for:
- Splunk used for KO tests
- req tests now use newest Splunk version

fix: adding splunk 9 support in tests

---

.github/workflows/reusable-build-test-release.yml

There is no need to create package/lib folder and put empty
requirements.txt file there if we do not have globalConfig.json
file present in the repository, which is the indicator of
the add-on which needs Python dependencies to be installed under
package/lib folder.

fix: don't create package/lib if no globalConfig.json file

---

.github/workflows/reusable-build-test-release.yml

Since firefox was removed to save credits in circleci, adding it back now to github actions to enhance the coverage as recently we found a bug in Firefox browser while executing GCP UI tests for Splunk Certification purpose.
Since this can introduce potential uncaught failures in addon, adding this as feat commit to give a choice/readiness time for dev teams to merge the minor version instead of a bugfix release that would directly add the firefox browser in all addons.

feat: added firefox browser config for UI tests

---

.github/workflows/reusable-build-test-release.yml

`splunk/addonfactory-test-matrix-action@v1.9` has a much smaller image (Python alpine versus plain Python) which will save a lot of time during the pipeline run.
This meta job for example took over 2 minutes to run https://github.com/splunk/splunk-add-on-for-google-workspace/actions/runs/5092899462/jobs/9154853661?pr=449#step:2:53.
The v1.9 version https://github.com/splunk/addonfactory-ucc-generator/actions/runs/5090618123/jobs/9149662805#step:2:1 took 3 seconds.

fix: bump splunk/addonfactory-test-matrix-action to v1.9

---

.github/workflows/reusable-build-test-release.yml

It does not work anyways and the contributor of this change is no longer working at Splunk. We can always restore it if we need in the future.
Tested change here: https://github.com/splunk/splunk-add-on-for-google-workspace/pull/457

fix: remove workflow_conclusion job

---

.github/workflows/reusable-build-test-release.yml

The `codecov` integration is not used by the devs, we can't remove `CODECOV_TOKEN` from secrets section in the pipeline, it needs to be synchronised with template changes, so this way we are not breaking anything.

fix: remove codecov after unit tests

---

.github/workflows/reusable-build-test-release.yml

Let's run unit tests and build using Python 3.11 in a preparation for the future changes.
Tested here: https://github.com/splunk/splunk-add-on-for-cisco-meraki/pull/408

feat: run unit tests and build for Python 3.11 as well

---

.github/workflows/reusable-build-test-release.yml
.pre-commit-config.yaml

- add concurrency to cancel running/pending workflows from same PR or pushed to same branch
- replace condition for job execution always() with !cancelled()
- reformatted multi-line strings with conditionals for job execution -  tested that this is only solution for github to work properly with !cancelled() and other conditions
- to all run-*-tests executed on argo added step `Cancel workflow` - now workflows sent by argo will be cancelled if github workflow is cancelled
Tested on:
https://github.com/splunk/splunk-add-on-for-google-workspace/actions/runs/5643680981/job/15289137706
https://github.com/splunk/splunk-add-on-for-cisco-meraki/actions/runs/5620072190/job/15289640068

feat: cancel gh workflow

---

.github/workflows/reusable-build-test-release.yml
.gitignore

Related [Jira](https://splunk.atlassian.net/browse/ADDON-63514).
This PR aims to remove the inconsistency with poetry usage for some of the repositories. We should block the build process if the `poetry.lock` file is not consistent with `pyproject.toml` file.
A run which fails when the `poetry.lock` is not consistent: https://github.com/splunk/splunk-add-on-for-cisco-meraki/actions/runs/6088301297/job/16518722640?pr=415#step:6:132
A run which does not fail when `poetry.lock` is consistent: https://github.com/splunk/splunk-add-on-for-google-workspace/actions/runs/6088352198/job/16518888626
A run which ignores this check because there is no `poetry.lock`: https://github.com/splunk/splunk-add-on-for-mysql/actions/runs/6088361196/job/16518900173?pr=422

feat: run poetry lock --check during the build

---

.github/workflows/reusable-build-test-release.yml

As LastPass is being deprecated in Splunk, we need to update related information and direct to Secret Server.
More info:
https://docs.google.com/document/d/1sRYlWG22gpEJyltgchP0RQMeBqsFAjhlDQiTspp9zgA/edit

chore: replace LastPass information with SecretServer

---

.github/workflows/reusable-build-test-release.yml

To follow up Python 3.7 EOL and 2.x Deprecation Program Page we need to be ready for python 3.9 with our apps.
As a first step let's monitor unit tests execution and build using python 3.9

fix: py39 unit tests

---

.github/workflows/reusable-build-test-release.yml

Related Jira: https://splunk.atlassian.net/browse/ADDON-63494
From time to time we can observe `time="2023-07-17T20:12:57.786Z" level=fatal msg="stream error: stream ID 1; INTERNAL_ERROR"` line during the text execution. This makes `run-tests` job to fail but still continues to run the tests in our infrastructure. After the tests are being finished it correctly collects all the test results.
This PR makes `run-tests` job to pass if any error occurred so the final decision on whether tests passed will be transferred to `test_report` step of the workflow.

fix: add continue-on-error to reusable wf

---

.github/workflows/reusable-build-test-release.yml

- bump addonfactory-test-matrix-action to v1.11 which includes unreleased splunk image with python 3.9 
- add to all tests step `Test Report Python 3.9` with `continue-on-error` option to run tests on python 3.9 and not fail workflows
- step `Test Report` is executed for all official splunk images, `Test Report Python 3.9` is executed only for not released splunk images with tag ~unreleased-python3_9
This approach enables the execution of tests on a Splunk image with Python 3.9 without causing the entire workflows to fail. However, the downside is that tests performed on Splunk with Python 3.9 consistently result with success. Therefore, it is necessary to manually verify the test outcomes to ensure the proper functioning of TA tests with Python 3.9.
Tests:
1. Tests failing, `pre-publish` …

fix: splunk python 3.9 tests handling

---

.github/workflows/reusable-build-test-release.yml

This PR updates `poetry` version to v1.5.1 in the reusable workflow. v1.5.1 is the last `poetry` version that can be used with Python 3.7.

feat(poetry): bump poetry version to v1.5.1

---

.github/workflows/reusable-build-test-release.yml

This commit renames semgrep action used due to a change upstream.
Testing here: https://github.com/splunk/splunk-add-on-for-amazon-web-services/pull/1098

fix: rename semgrep action

---

.github/workflows/reusable-build-test-release.yml

Changes related to recently reported issues with tests running on unreleased Splunk with python 3.9
1. Instead of relying on addonfactory-test-matrix, matrix elements are included in each test job to cover testing on splunk python3.9
2. to avoid reaching github timeout limit 6hrs, causing uncontrolled workflow failure, steps capture-start-time and calculate-timeout are introduced to each test job. Their output is being used to determine timeout-minutes parameter for according steps.
Tested:
* https://github.com/splunk/splunk-add-on-for-google-workspace/actions/runs/6790469522
* https://github.com/splunk/splunk-add-on-for-microsoft-cloud-services/actions/runs/6812742326
* https://github.com/splunk/splunk-add-on-for-amazon-web-services/actions/runs/6802760261

fix: timeout control and python39 splunk tests include in matrix

---

.github/workflows/reusable-build-test-release.yml

Reduced the calculated remaining_time_minutes from 360 to 350 to ensure that the timeout-minutes is set to a value lower than the time remaining before the github job is forcefully canceled due to the 360-minute limit.

fix: decrease expected maximum job time to 350mins

---

.github/workflows/reusable-build-test-release.yml

Fixing a issue when workflow `github.ref_name` was causing undesired cancellation of other running workflows.
This condition is too broad.

fix: align concurrency groups

---

.github/workflows/reusable-build-test-release.yml

Rationale:
There is no point in running appinspect api for particular tags if we run for all.
https://splunk.slack.com/archives/CBFTW8QRG/p1700059679560229

fix: run appinspect-api only on all tags by default

---

.github/workflows/reusable-build-test-release.yml
README.md

So far, PRs to `main` by default have all the tests enabled. Applying labels to enable particular tests is available only for PRs that are not to `main`.
Our team doesn't use `develop` branch, thus we need to be able to skip some tests on PRs to `main` - to get feedback quickly.
- This PR makes it possible to use labels for enabling/disabling tests also on PRs to `main`.
-  apart from test labels (`execute_knowledge`, etc.), `use_labels` label has to be applied to the PR before (re)opening it to make test labels work - this is to ensure that execution of all tests is still the default option for PRs to `main`
PR: https://github.com/splunk/splunk-add-on-for-microsoft-cloud-services/pull/993
Workflow runs:
- with `use_labels` label: …

feat: use labels for test execution on PRs to main

---

.github/workflows/reusable-build-test-release.yml

This PR updates splunk/addonfactory-test-matrix-action to v1.13 which includes Splunk version updates:
* 9.1.1 -> 9.1.2
* 9.0.6 -> 9.0.7

feat: update splunk/addonfactory-test-matrix-action to v1.13

---

.github/workflows/build-test-release.yaml
.github/workflows/reusable-build-test-release.yml

This updates every dependency that is not being run on container `ghcr.io/splunk/workflow-engine-base` as it does not support node20 in current version.
Updated depenencies:
- apache/skywalking-eyes@v0.5.0
- actions/setup-python@v5
- amannn/action-semantic-pull-request@v5.4.0
- docker/metadata-action@v5.4.0
- crazy-max/ghaction-virustotal@v4
- splunk/appinspect-cli-action@v2.0
- docker/setup-buildx-action@v3
Tested here: https://github.com/splunk/splunk-add-on-for-cisco-meraki/actions/runs/7396274137

feat: update appinspect-cli to 2.0 and other dependencies

---

.github/workflows/reusable-build-test-release.yml

This PR regards https://splunk.atlassian.net/browse/ADDON-67617
It introduces dynamic change of pre-publish job which was necessary to avoid confusion while creating PR towards main branch having had pushed to develop branch. 
tests: 
- pr: https://github.com/splunk/splunk-add-on-for-mysql/pull/464
- push to develop workflow (name has been changed): https://github.com/splunk/splunk-add-on-for-mysql/actions/runs/7399079510
- pr to main workflow (name remains intact): https://github.com/splunk/splunk-add-on-for-mysql/actions/runs/7399125452

feat: pre-publish job adjusted to triggering event

---

.github/workflows/build-test-release.yaml
.licenserc.yaml
.releaserc
README.md

This PR proposes to use `develop` branch as a development branch keeping `main` branch stable in case of necessary bug fixes.
The proposed flow (documented in the README as well):
* we make our development in `develop` branch
* once we are ready to release, we make a PR from `develop` to `main` branch, after the merge new tags will be created from the main `branch`
* go to first step in this list
In case we need to release a bug fix - we can create a PR to main, merge it, new tags will be created, issue is solved and we can cherry-pick this commit to the `develop` branch. The similar scenario is working in the UCC repository right now and the results are quite good.
We can go even further and make a develop branch a default one in this GitHub repository.
This PR removes existing …

ci: make development in develop branch possible

---

.github/workflows/reusable-build-test-release.yml
README.md

This PR update semgrep job in the reusable-build-test-release.ym. 
The change was necessary, because previously used semgrep-action was deprecated.
Jira: https://splunk.atlassian.net/browse/ADDON-67642
Tested on: https://github.com/splunk/test-addonfactory-repo/actions/runs/7421872771/job/20196096465

refactor: semgrep job update

---

.github/workflows/reusable-build-test-release.yml

Fix for reported [ADDON-67588](https://splunk.atlassian.net/browse/ADDON-67588) problem with installation of internal repositories.
In `reusable-build-test-release.yml` GH_TOKEN_ADMIN is used for authentication against https://github.com
In `test-addon.sh` GITHUB_USERNAME and GITHUB_PASSWORD are used for authentication against https://github.com
Related PR:
https://github.com/splunk/ta-automation-k8s-manifests/pull/75
Tested on:
https://github.com/splunk/splunk-add-on-for-microsoft-cloud-services/actions/runs/7468842506/job/20340167700

fix: ADDON-67588 internal repo installation

---

.github/workflows/reusable-build-test-release.yml

We are generally using ssh key for development instead of https.
this will support both cases in requirements.txt and poetry
Poetry example:
```
splunksdc = {git = "https://github.com/splunk/splunksdc.git", tag = "v0.1.2"}
splunksdc = {git = "ssh://git@github.com/splunk/splunksdc.git", tag = "v0.1.2"}
```

chore: github dependencies support for ssh

---

.github/workflows/reusable-build-test-release.yml

tested here: https://github.com/splunk/splunk-add-on-for-crowdstrike-fdr/actions/runs/7612474417/job/20730350677?pr=823

chore: update appinspect-cli to 2.2

---

.github/workflows/reusable-build-test-release.yml

release notes: 
- fix: openapi.json path https://github.com/splunk/addonfactory-workflow-addon-release/pull/220
- chore: github dependencies support for ssh https://github.com/splunk/addonfactory-workflow-addon-release/pull/219
- chore: update appinspect-cli to 2.2 https://github.com/splunk/addonfactory-workflow-addon-release/pull/222

fix(release): v4.15.1

---

.github/workflows/reusable-build-test-release.yml

- Downgrade dorny/test-reporter action to `v1.7.0` as `v1.8.0` relies on node20 which is not supported in currently used `workflow-engine-base:2.0.3`
- Bump version of unreleased splunk with python3.9 to latest available build.
Tested here:
https://github.com/splunk/splunk-add-on-for-google-workspace/actions/runs/7693652729/job/20963434508
This PR will be followed by backporting of same changes to `reusable-build-test-release v4.6`

fix: downgrade dorny/test-reporter to v1.7.0 and bump unreleased Python version

---

.github/workflows/reusable-build-test-release.yml

This PR removes firefox from ui tests execution, since firefox is ranked 4th in Desktop Browser Market Share Worldwide.
https://splunk.atlassian.net/browse/ADDON-68235
tested here: https://github.com/splunk/test-addonfactory-repo/actions/runs/7815971598/job/21320701943

feat: remove firefox from ui tests

---

.github/workflows/reusable-build-test-release.yml

This PR removes addonfactory-packaging-toolkit-action from the workflow and replaces it with direct logic. It also skips the step of partitioning so release on GitHub only contains files that are used by the developers.
https://splunk.atlassian.net/browse/ADDON-68239
Tested here: https://github.com/splunk/test-addonfactory-repo/actions/runs/7902209078
Example release : https://github.com/splunk/test-addonfactory-repo/releases/tag/v0.7.2

feat(release): addonfactory packaging toolkit action removal

---

.github/workflows/reusable-build-test-release.yml

Added parameters to simplify the process of making changes and testing argo related stuff
Tested here: 
https://github.com/splunk/splunk-add-on-for-cisco-meraki/actions/runs/7979596198 Backwards compatibility
https://github.com/splunk/splunk-add-on-for-okta-identity-cloud/actions/runs/7986170413/job/21806162151 staging

refactor: introduce parameters to control argo environment

---

.github/workflows/reusable-build-test-release.yml

Image 2.0.12 uses git 2.39 and 2.0.3 uses 2.32. This error was intoduced with git 2.36. It requires setting up safe directory (probably here is some other way to fix it, but this works)
Tested here: 
- https://github.com/splunk/splunk-add-on-for-google-workspace/actions/runs/8005834200
- https://github.com/splunk/splunk-add-on-for-cisco-meraki/actions/runs/8005821163

chore: update wfe-base and set up git safe directory

---

.github/workflows/reusable-build-test-release.yml

Release: https://github.com/splunk/appinspect-cli-action/releases/tag/v2.3.0
Release notes: https://dev.splunk.com/enterprise/docs/relnotes/relnotes-appinspectcli/whatsnew/#v3302024-03-04
Test PR: https://github.com/splunk/splunk-add-on-for-google-workspace/pull/537

fix: update AppInspect CLI action to v2.3

---

.github/workflows/reusable-build-test-release.yml

Release:
https://github.com/splunk/appinspect-cli-action/releases/tag/v2.3.0 Release notes:
https://dev.splunk.com/enterprise/docs/relnotes/relnotes-appinspectcli/whatsnew/#v3302024-03-04
Test PR:
https://github.com/splunk/splunk-add-on-for-google-workspace/pull/537

fix: update AppInspect CLI action to v2.3 (#238)

---

.github/workflows/reusable-build-test-release.yml

Release:
https://github.com/splunk/appinspect-cli-action/releases/tag/v2.4.0 Release notes:
https://dev.splunk.com/enterprise/docs/relnotes/relnotes-appinspectcli/whatsnew/#v3402024-03-14
Test PR: 
https://github.com/splunk/splunk-add-on-for-google-workspace/actions/runs/8297872866

fix: update AppInspect CLI action to v2.4

---

.github/workflows/reusable-build-test-release.yml

Release:
https://github.com/splunk/appinspect-cli-action/releases/tag/v2.4.0 Release notes:
https://dev.splunk.com/enterprise/docs/relnotes/relnotes-appinspectcli/whatsnew/#v3402024-03-14
Test PR: 
https://github.com/splunk/splunk-add-on-for-google-workspace/actions/runs/8297872866

fix: update AppInspect CLI action to v2.4 (#241)

---

.github/workflows/reusable-build-test-release.yml

Added stage to combine splunk versions an use it in modinput test job.
Job in AWS addon where modinut is running successfully with python3.9 (Matrix of 24 jobs 3*8): https://github.com/splunk/splunk-add-on-for-amazon-web-services/actions/runs/8431526533
Job in MSCS addon : https://github.com/splunk/splunk-add-on-for-microsoft-cloud-services/actions/runs/8431532363

fix: combining splunk versions

---

.github/workflows/reusable-build-test-release.yml

Release version 2.5 for reusable build test release.
[https://github.com/splunk/appinspect-cli-action/releases/tag/v2.5.0](url)
[https://dev.splunk.com/enterprise/docs/relnotes/relnotes-appinspectcli/whatsnew/#v3502024-03-27](url)
[https://github.com/splunk/splunk-add-on-for-google-workspace/actions/runs/8464669953](url)

fix: update AppInspect CLI action to v2.5

---

.github/workflows/reusable-build-test-release.yml

Poetry is being used for deps installation in unit tests jobs before build job, hence moving poetry lock --check to unit tests jobs.
Test run: https://github.com/splunk/splunk-add-on-for-google-workspace/pull/543

fix: move poetry lock --check to unit tests job

---

.github/workflows/reusable-build-test-release.yml

- Update reusable workflow according to updated handling of python 3.9 tests
- Job in AWS addon where all the relevent  test is running successfully with python3.9: [Job](https://github.com/splunk/splunk-add-on-for-amazon-web-services/actions/runs/8687485637/job/23821632227)
- Addon Job for MSCS :- [Job](https://github.com/splunk/splunk-add-on-for-microsoft-cloud-services/actions/runs/8683988655)
- Updated workflow so that steps combined_Splunkmatrix and python39_splunk in job meta are merged into single step.
- Updated workflow so these tests are being executed the same way for all the other test types

fix: combining splunk versions for python3.9 matrix issues

---

.github/workflows/reusable-build-test-release.yml

Currently in unit tests we install dependencies from requirements_dev.txt file, exported by poetry.
The problem is that this requirements_dev.txt file contains environment markers with supported versions of pythons - this format causes pip to exit silently ans setup step is successful - job is failing later on run-test step which is unexpected.
Changed installation method to `poetry install`
Tests:
https://github.com/splunk/splunk-add-on-for-google-workspace/pull/547
https://github.com/splunk/splunk-add-on-for-amazon-web-services/pull/1221

fix: change deps installation method in unit tests

---

.github/workflows/reusable-build-test-release.yml

Disable all delay-destroy switches to prepare to deprecate this functionality
Test run:
https://github.com/splunk/splunk-add-on-for-okta-identity-cloud/actions/runs/8986563964

fix: disable delay-destroy for all stages

---

.github/workflows/reusable-build-test-release.yml

This PR changes default version of ta-automation-k8s-manifests to this tag: [v1.0.0](https://github.com/splunk/ta-automation-k8s-manifests/releases/tag/v1.0.0)
Tested here: https://github.com/splunk/splunk-add-on-for-mysql/pull/484

fix: change k8s-manifest-default-branch

---

.github/workflows/reusable-build-test-release.yml

This PR changes default version of ta-automation-k8s-manifests to this tag:
[v1.0.0](https://github.com/splunk/ta-automation-k8s-manifests/releases/tag/v1.0.0)
Tested here: https://github.com/splunk/splunk-add-on-for-mysql/pull/484

fix: change k8s-manifest-default-branch (#266)

---

.github/workflows/reusable-build-test-release.yml

https://github.com/splunk/appinspect-cli-action/releases/tag/v2.7.0
https://github.com/splunk/appinspect-cli-action/pull/128
https://github.com/splunk/splunk-add-on-for-google-workspace/actions/runs/9017761710

fix: update AppInspect CLI action to v2.7

---

.github/workflows/reusable-build-test-release.yml

PR fixes reported recently issue - test jobs are failing on upload-artifact action v4 because of duplicated artifacts names in workflow.
More details:
https://splunk.slack.com/archives/CRTNPEZ4M/p1716901843632889
Tested:
https://github.com/splunk/splunk-add-on-for-amazon-web-services/actions/runs/9271058930/job/25517805310

fix: upload artifact naming update 

---

.github/workflows/build-test-release.yaml
.github/workflows/reusable-build-test-release.yml
README.md
renovate.json
runbooks/publish_multiple_os_images_scripted_inputs.md

Test runs:
https://github.com/splunk/splunk-add-on-for-amazon-web-services/actions/runs/9269557494
https://github.com/splunk/test-addonfactory-repo/actions/runs/9270329208
Changes possibly affecting customers:
- add ui_marker to enable splitting UI tests execution
- fix for failing upload-artifact@v4 due to multiple artifacts with same name
- replace edplato/trufflehog-actions-scan action with official trufflehog action latest release
- bump version of workflow-engine-base image to v4.0 (Ubuntu 20 -> Ubuntu 22)
Changes not affecting customers:
- wfe-test-runner-action update to v5 and change of the way that browser is determined in k8s 
- docs and ci related updates
Also note that starting from release v4.16.0 some assets are removed from TA releases:
1. installation-actions.json
2. …

chore(release): merge develop to main

---

.github/workflows/reusable-build-test-release.yml

This PR updates `workflow-engine-base` version from 4.0.0 to 4.1.0 - which in turn updates `kubectl` version from 1.22.0 to 1.28.0. It also bumps k8s-manifests-branch default value ( [check the difference here](https://github.com/splunk/ta-automation-k8s-manifests/compare/v3.0.0...v3.0.1) )
`wfe-test-runner-action` is not being updated in this PR, since it's set to v5.0 (which points to v5.0.1)
The change was required to fix the issue of copying big diag files by adding `--retries` flag, which was not available in version 1.22.0.
Jira: https://splunk.atlassian.net/browse/ADDON-69486 
Test run: https://github.com/splunk/splunk-add-on-for-google-workspace/actions/runs/9351735473

fix: update kubectl version

---

.github/workflows/reusable-build-test-release.yml

Updated matrix action to v2.0.0
- Tested with mscs: https://github.com/splunk/splunk-add-on-for-microsoft-cloud-services/actions/runs/9381867898

fix: update addonfactory-test-matrix-action version

---

.github/workflows/reusable-build-test-release.yml

`sudo pip3 install poetry` causes issues with dependencies installation as runners `python` is being used instead of `python` checked out in earlier step.
Tests: https://github.com/splunk/splunk-add-on-for-google-workspace/actions/runs/9612424171

fix: setup job install poetry without sudo

---

.github/workflows/reusable-build-test-release.yml

Update image of unreleased splunk with python 3.9 to build https://cd.splunkdev.com/splcore/main/-/tree/f8b1a92a256b (Splunk 9.3)
Tests: 
https://github.com/splunk/splunk-add-on-for-servicenow/actions/runs/9692653841/job/26746592496?pr=741
https://github.com/splunk/splunk-add-on-for-google-cloud-platform/actions/runs/9692491380/job/26746170582?pr=735
To be released as a bugfix.

fix: update unreleased splunk docker image

---

.github/workflows/reusable-build-test-release.yml

Update image of unreleased splunk with python 3.9 to build https://cd.splunkdev.com/splcore/main/-/tree/f8b1a92a256b (Splunk 9.3)
Tests: 
https://github.com/splunk/splunk-add-on-for-servicenow/actions/runs/9692653841/job/26746592496?pr=741
https://github.com/splunk/splunk-add-on-for-google-cloud-platform/actions/runs/9692491380/job/26746170582?pr=735 To be released as a bugfix.

fix: update unreleased splunk docker image (#294)

---

.github/workflows/reusable-build-test-release.yml

List of OSs for scripted inputes tests can be provided as an input to reusable workflow.
Tested: https://github.com/splunk/splunk-add-on-for-unix-and-linux/pull/577

fix: add input for scripted inputs os

---

.github/workflows/reusable-build-test-release.yml

bump matrix-action to v2.0.2 which includes sc4s v3.28.0
tests:
https://github.com/splunk/splunk-add-on-for-cisco-esa/pull/440
Report before update (58 KO failures) https://github.com/splunk/splunk-add-on-for-cisco-esa/runs/27652534705
report after update (12 KO failrues) https://github.com/splunk/splunk-add-on-for-cisco-esa/runs/27656994881

fix: bump matrix-action to v2.0.2

---

.github/workflows/reusable-build-test-release.yml

bump matrix-action to v2.0.2 which includes sc4s v3.28.0 tests:
https://github.com/splunk/splunk-add-on-for-cisco-esa/pull/440 Report before update (58 KO failures)
https://github.com/splunk/splunk-add-on-for-cisco-esa/runs/27652534705 report after update (12 KO failrues)
https://github.com/splunk/splunk-add-on-for-cisco-esa/runs/27656994881

fix: bump matrix-action to v2.0.2 (#299)

---

.github/workflows/reusable-build-test-release.yml

This release of manifests doubles the CPU for `modinput_functional` tests.
Ref: https://github.com/splunk/ta-automation-k8s-manifests/pull/96

fix: bump k8s-manifests branch to v3.0.3

---

.github/workflows/reusable-build-test-release.yml

This release of manifests doubles the CPU for `modinput_functional` tests.
Ref: https://github.com/splunk/ta-automation-k8s-manifests/pull/96

fix: bump k8s-manifests branch to v3.0.3 (#301)

---

.github/workflows/reusable-build-test-release.yml

In certain scenarios, some clients prefer not to update to the latest version of the software but require critical bug fixes in their current version. This necessitates bypassing the automated versioning provided by semantic-release, allowing for a manually specified version to be released.
In this PR, I've introduced a dispatcher to the workflow, enabling users to specify a custom version when triggering a release. This enhancement provides greater flexibility, particularly for clients who need targeted updates without adopting the latest release.
* Custom-Version Dispatcher: Added a dispatcher that allows users to input a custom version number when initiating a release. This ensures that specific bug fixes can be released independently of the standard semantic-release process.
* Release …

feat: add publish for custom version

---

.github/workflows/reusable-build-test-release.yml

Updated the build-test-release workflow to use [sast-scan](https://github.com/splunk/sast-scanning) owned by product security team instead of using custom implementation.
Ref: https://splunk.atlassian.net/browse/ADDON-72309
Test workflow run: https://github.com/splunk/splunk-add-on-for-servicenow/actions/runs/10596615468
Tested on PR: https://github.com/splunk/splunk-add-on-for-servicenow/pull/751
Workflow is not tested for the failure scenario because we need to have blocker findings by the semgrep in order to fail the workflow. Currently all rules are in monitor mode so any findings by the semgrep will be non-blocker resulting in semgrep stage to pass everytime.
Discussion with the semgrep team: https://splunk.slack.com/archives/C011ELTV7FG/p1724923496371529

refactor: use reusable workflow for semgrep

---

.github/workflows/reusable-build-test-release.yml
README.md

Updating README.md to be aligned with the latest changes (https://github.com/splunk/addonfactory-workflow-addon-release/pull/309).

docs: update setup-workflow description in README.md

---

.github/workflows/reusable-build-test-release.yml

This PR bumps `k8s-manifests-branch` version.  It increases requests rate limit for GitHub api. Related PR https://github.com/splunk/ta-automation-k8s-manifests/pull/103
Tested here: https://github.com/splunk/splunk-add-on-for-amazon-web-services/actions/runs/10697833642/job/29656542503

fix: bump k8s manifests branch version

---

.github/workflows/reusable-build-test-release.yml

This PR bumps `k8s-manifests-branch` version.
It fixes the below items,
- Stopped the diag generation in case of passed tests
- fixed cim-compliance-report generation
Related PRs:
(Stop diag generation)
- https://github.com/splunk/ta-automation-app-of-apps/pull/21
- https://github.com/splunk/ta-automation-k8s-manifests/pull/104
- https://cd.splunkdev.com/workflow-engine/ta/ta-automation-cluster/-/merge_requests/63
(fix cim-compliance-report)
- https://github.com/splunk/ta-automation-k8s-manifests/pull/105
Test workflow run: https://github.com/splunk/splunk-add-on-for-mysql/actions/runs/10767934733/job/29856231470

fix: bump k8s-manifests-branch version

---

.github/pull_request_template.md
.github/workflows/reusable-build-test-release.yml
README.md

Fix the issue where automated releases where not created due to incorrect conditions for pre-publish job.
Tests:
PR scenario: https://github.com/splunk/test-addonfactory-repo/actions/runs/11027730555
release scenario: https://github.com/splunk/test-addonfactory-repo/actions/runs/11028553116
custom version release: https://github.com/splunk/test-addonfactory-repo/actions/runs/11047251558

fix: publish conditions

---

.github/workflows/reusable-build-test-release.yml

This PR resolves the issue with the test results summary.
Also, fixed the issue with the `test-btool` workflow status check.
Issue reference:
workflow run: https://github.com/splunk/splunk-add-on-for-amazon-web-services/actions/runs/12072808241
check the ucc modinput tests results summary. It shows total number of tests and the errors count as 6. However, if you check the test report, there were only 3 tests ran(each test case had error in the setup and teardown method resulting in 6 errors).
Test workflow: https://github.com/splunk/splunk-add-on-for-amazon-web-services/actions/runs/12136591898

fix: workflow summary for tests results

---

.github/pull_request_template.md
.github/workflows/build-test-release.yaml
.github/workflows/reusable-build-test-release.yml
README.md

This PR adds the feature to run the `ucc_modinput_functional` tests seperately from `modinput_functional` (Legacy).
Reference: https://splunk.atlassian.net/browse/ADDON-75556
Test run: 
https://github.com/splunk/splunk-add-on-for-salesforce/actions/runs/11473918131
https://github.com/splunk/splunk-add-on-for-google-cloud-platform/actions/runs/12067263557

feat: run both ucc and legacy modinput tests

---

.github/workflows/reusable-build-test-release.yml

This PR adds input block_mode for semgrep to enable failing pipeline if we have some findings in semgrep scan.
Test run: https://github.com/splunk/splunk-add-on-for-google-workspace/actions/runs/10954006775

fix: add block_mode input for semgrep

---

.github/workflows/reusable-build-test-release.yml

This PR fixes the issue with the deletion of the result summary artifacts for ucc modinput tests

fix: deletion of ucc modinput summary artifacts

---

.github/workflows/reusable-build-test-release.yml

This PR upgrades `trufflesecurity/trufflehog` action to `v3.85.0`
https://github.com/splunk/splunk-add-on-for-cisco-meraki/actions/runs/12201434038/job/34039826531?pr=491

chore(deps): upgrade trufflehog to 3.85.0

---

.github/workflows/reusable-build-test-release.yml

This is not a breaking change for the reusable workflow, updating version of the action to v3.0.
This PR will be followed up with a template change.
Tested - https://github.com/splunk/addonfactory-ucc-generator/pull/1525.

feat: update matrix action to v3.0

---

.github/workflows/reusable-build-test-release.yml

TA-> TA Upgrade implementation ADDON-73792
This pull request introduces a new feature to our CI/CD pipeline, focusing on automating upgrade testing for Technology Add-ons (TA). The goal is to streamline the release process by incorporating scalable and user-friendly solutions capable of executing upgrade scenarios
Key Features:
Automated Upgrade Testing: Introduces jobs for upgrade testing within the GitHub CI/CD pipeline.
Flexible Version Testing: Allows users to provide multiple TA versions on which upgrade tests should be executed. In this repo, ta_upgrade_version parameter is responsible for passing the info about versions being tested. Also, both GitHub and Splunkbase releases are supported, depending on the format of the version string provided:
vX.X.X - for GitHub releases
X.X.X - …

feat: upgrade tests

---

.github/workflows/reusable-build-test-release.yml

This updates k8s-manifests and runner image versions so that upgrade tests can run correctly.

fix: update versions for upgrade tests

---

.github/workflows/reusable-build-test-release.yml

This PR is addressing issue with deps installation when multiple pods are trying to install deps in the same time:
https://splunk.atlassian.net/browse/ADDON-78266
To be reviewed together with: https://github.com/splunk/ta-automation-k8s-manifests/pull/116
virtual environment is first build on github runner filesystem, site-packages are passed to aws s3, and finally downloaded directly to the empty venv on pods filesystem.
https://github.com/splunk/splunk-add-on-for-amazon-web-services/actions/runs/13140796010/job/36787923223
https://github.com/splunk/splunk-add-on-for-google-workspace/actions/runs/13153265349/job/36784656491

fix: deps handling from gh runner to pod

---

.github/workflows/reusable-build-test-release.yml

Reusable workflow fails in setup -> `modinput-test-prerequisites` ignores `ssh://` protocol in poetry.lock/pyproject.toml
```
[tool.poetry.group.modinput.dependencies]
splunk_add_on_ucc_modinput_test = {git = "ssh://git@github.com/splunk/addonfactory-ucc-test.git", tag = "v0.2.0"}
pytest-xdist = ">=3.5.0"
```
Example Job:
https://github.com/splunk/splunk-add-on-for-amazon-web-services/actions/runs/13052937673/job/36605381881
```
HangupException
The remote server unexpectedly closed the connection.
at /opt/hostedtoolcache/Python/3.7.17/x64/lib/python3.7/site-packages/dulwich/protocol.py:215 in read_pkt_line
211│ 
212│         try:
213│             sizestr = read(4)
214│             if not sizestr:
→ 215│                 raise HangupException
216│             size = int(sizestr, 16)
217│ …
```

fix: setup job to suport ssh github path in poetry

---

.github/workflows/reusable-build-test-release.yml

Limit test executions for scheduled runs to only latest Splunk version
https://github.com/splunk/test-addonfactory-repo/actions/runs/13200963135

fix: limit scheduled runs to latest Splunk

---

.github/workflows/reusable-build-test-release.yml

Bump trufflehog from `3.85.0` to `v3.88.5`
https://github.com/splunk/splunk-add-on-for-cisco-meraki/actions/runs/13243642192/job/36964695234

chore(deps): update trufflehog

---

.github/workflows/reusable-build-test-release.yml

Fix missng for upgrade tests: https://github.com/splunk/splunk-add-on-for-amazon-web-services/actions/runs/13251113562/job/36989972917

fix: add apt-get update to upgrade tests

---

.github/workflows/reusable-build-test-release.yml

Upgrade tests exclusions for automatic execution on PRs to main, etc. (defined here: https://github.com/splunk/addonfactory-workflow-addon-release/blob/main/.github/workflows/reusable-build-test-release.yml#L176) were not working because the condition for `run-upgrade-tests` job added in this PR was missing.
Running upgrade tests automatically on all events the same way as other test types is not desired right now. As per current design, upgrade tests should be executed only when explicitly specified - by assigning `execute_upgrade` label.
- all tests (including upgrade tests) automatically executed before implementing the fix: https://github.com/splunk/splunk-add-on-for-amazon-web-services/actions/runs/13540341896
- all tests (except upgrade tests) automatically executed after …

fix: skip automatic upgrade tests execution on PRs to main

---

.github/workflows/reusable-build-test-release.yml

Upgrade tests execution based on labels wasn't configured properly.  Due to variable name of the job output being incorrect, the upgrade tests were not executed when the `execute_upgrade` label was assigned to the PR.
- workflow without the fix - upgrade tests **not executed** with `execute_upgrade` label assigned: https://github.com/splunk/splunk-add-on-for-google-cloud-platform/pull/798/checks?sha=7797eec5e91a83687fd47ab458d641ac25fcb131
- workflow after the fix - upgrade tests **executed properly** with `execute_upgrade` label assigned: https://github.com/splunk/splunk-add-on-for-google-cloud-platform/pull/798/checks?sha=cb6b6febff5f5580fa44ccab1c6c0a79b21d454e

fix: fix labeled execution for upgrade tests

---

.github/workflows/reusable-build-test-release.yml

It is too expensive to run all WFE tests on all supported Splunk versions on every commit in CDC add-ons on every commit / PR. Let TA to specify the condition to run WFE tests on latest only. 
* Full run takes 2d 20h 31m 27s https://github.com/splunk/splunk-add-on-for-amazon-web-services/actions/runs/13389640676/usage
* Latest run takes 17h 29m 24s https://github.com/splunk/splunk-add-on-for-amazon-web-services/actions/runs/13478849153/usage
Default condition - Run WFE tests on all Splunk Versions for conditions:
*  push to main, develop
* PR to main
Run only on Splunk latest when:
* scheduled execution
* Everything else
Introduce `wfe-run-on-splunk-latest` input for TA to be precise when it needs a custom rule to run or not run on latest
`Summary of Versions Used` should take its value …

fix: wfe tests run on splunk latest

---

.github/workflows/reusable-build-test-release.yml

Run `appinspect api` job for `release/` branches in `build-test-release` pipeline
Ticket: https://splunk.atlassian.net/browse/ADDON-77779
Tested in the following cases where appinspect api job is:
- Running for PR with “release/“ base: https://github.com/splunk/splunk-add-on-for-microsoft-cloud-services/actions/runs/13626390125
- Running for manual trigger on “release/“ branch: https://github.com/splunk/splunk-add-on-for-microsoft-cloud-services/actions/runs/13626413937
- Not running for chore/ branch: https://github.com/splunk/splunk-add-on-for-microsoft-cloud-services/actions/runs/13626445165

chore: run appinspect api on release branches

---

.github/workflows/reusable-build-test-release.yml

Added a new job validate-docs-change.
This job will attempt to serve the documentation and fail if there are any errors.
If errors occur, they will be printed in the check logs step.
Another stage, enforce-docs-changes, reviews the result of validate-docs-change and uses run metadata to determine whether the job should fail the pipeline.
When the PR targets the main branch, enforce-docs-changes will enforce failure on broken documentation and block merge.
For other branches, it serves as an indicator of documentation issues without blocking the merge.

feat: adding docs change validation step in reuseable CI

---

runbooks/update_appinspect_cli_action.md

I think it makes more sense to make a fix release each time we update appinspect version. We'd prevent ourselves from rolling out the template each time there is a feat release of appinspect. 
No tests are needed

docs: change the runbok for appinspect update

---

.github/workflows/reusable-build-test-release.yml

Bump version of k8s-manifests to the version with fix for selenium pull rates issues
tests: https://github.com/splunk/splunk-add-on-for-amazon-web-services/pull/1460

fix: mitigate selenium pull rate limits

---

.github/workflows/reusable-build-test-release.yml

update appinspect-cli-action to 2.10

fix: update AppInspect CLI action to v2.10

---

.github/workflows/reusable-build-test-release.yml

This reverts commit e30a82125a96eb0c8010c5c81b133e95106ee06b.
This PR reverts the previous implementation of documentation validation and enforcement, and reintroduces those capabilities using a **reusable GitHub Actions workflow** along with a **template `validate-deploy-docs.yml` workflow file** in the template repository.
- Removes the hardcoded docs validation logic.
- Changes related to document validation and deployment is made in this PR: https://github.com/splunk/addonfactory-repository-template/pull/743

Revert "feat: adding docs change validation step in reuseable CI (#390)"

---

.github/workflows/reusable-build-test-release.yml

This is an adaptation to the new interface of the `ucc-test-modinput` command. From now on `ucc-test-modinput` does not perform `ucc-test-modinput gen` by default, so it must be explicitly specified.

fix: add adjustments to ucc-test-modinput interface

---

.github/workflows/reusable-build-test-release.yml

This PR bumps k8s repository version. 
k8s changes are related to vendor installation for ucc modinput tests. 
Full Changelog: https://github.com/splunk/ta-automation-k8s-manifests/compare/v3.3.3...v3.3.4
- https://github.com/splunk/splunk-add-on-for-tomcat/actions/runs/15702434384
- https://github.com/splunk/splunk-add-on-for-palo-alto-networks/actions/runs/15702466025

fix: adjust k8s to ucc modinput tests

---

.github/workflows/reusable-build-test-release.yml

This PR bumps the k8s-manifessts-branch from v3.5.1 to v3.6.1. It contains the following changs
- Updates in the env variable for sc4s setup for compatibility with v3.37.0
- New argument `ta-version` added in the pre-upgrade tests 
- https://github.com/splunk/splunk-add-on-for-google-cloud-platform/actions/runs/16213562635
- https://github.com/splunk/splunk-add-on-for-microsoft-office-365/actions/runs/16213242733
(failures in the upgrade tests are not due to changes. Changes just affect the sc4s setup and pre-upgrade test execution and they are getting executed.)

fix: bump k8s manifests

---

.github/workflows/reusable-build-test-release.yml

Use `env` for Python version handling instead of `input`
Update Poetry to latest version `2.1.4`
Use `features` input for addonfactory-test-matrix-action to filter out non compatible Splunk versions
https://github.com/splunk/splunk-add-on-for-microsoft-office-365/actions/runs/16799304299

fix: pin Python 3.9 and filter Splunk images

---

.github/workflows/reusable-build-test-release.yml

Currently for test report if there are multiple blocks in the testcase tag (i.e error + failure) then it will count both and resulting summary may not align correctly. This PR updates the logic for report summary.
o365: https://github.com/splunk/splunk-add-on-for-microsoft-office-365/actions/runs/16805102170?pr=858

fix: Resolve discrepancies in test outcome counting

---

.github/workflows/reusable-build-test-release.yml

Warn when `centaurs` is used.
* https://github.com/splunk/splunk-add-on-for-microsoft-office-365/actions/runs/17073350867/job/48408007804?pr=863

feat: warn not to use centaurs

---

.github/workflows/reusable-build-test-release.yml

This PR brings the code from https://github.com/splunk/addonfactory-ucc-generator-action/tree/main and aims to deprecate this repository in favor of supporting less.
* https://github.com/splunk/splunk-add-on-for-okta-identity-cloud/pull/373 - I downloaded the built add-on and it looks okay but I did not check every single file

refactor: directly build add-on
